### ISSUE TITLE
Not working on (ancient) CentOS 5

### ISSUE THREAD

**Issue by wakkowarner** [splattael/libnotify#31]
Function 'notify_notification_set_hint_uint32' not found in [libnotify.so]

```
[jenkins@ci adrenalyn]$ strings /usr/lib64/libnotify.so.1.1.0 | grep notify_notification_set_hint
notify_notification_set_hint_string
notify_notification_set_hint_byte_array
notify_notification_set_hint_byte
notify_notification_set_hint_double
notify_notification_set_hint_int32
notify_notification_set_hint_string
notify_notification_set_hint_byte_array
notify_notification_set_hint_byte
notify_notification_set_hint_double
notify_notification_set_hint_int32
[jenkins@ci adrenalyn]$ gem list | grep libnotify
libnotify (0.9.1)
[jenkins@ci adrenalyn]$ rpm -qf /usr/lib64/libnotify.so.1.1.0
libnotify-0.4.2-6.el5
[jenkins@ci adrenalyn]$ 
```

**Comment by splattael** [comment]
Thanks for reporting!

`libnotify` renamed `notify_notification_set_hint_int32` to `notify_notification_set_hint_uint32` in version 0.4.5.
See docs for [0.4.4](http://libnotify.sourcearchive.com/documentation/0.4.4/notification_8c_cc7444ad7478869c36065c6630f53309.html#cc7444ad7478869c36065c6630f53309) and [0.4.5](http://libnotify.sourcearchive.com/documentation/0.4.5/notification_8c_04c5ea0d2ff4aa7677acc1f6f6f9d499.html#04c5ea0d2ff4aa7677acc1f6f6f9d499.

I'll try to work around this soonish.

**Comment by splattael** [comment]
Well, 3 year later. No progress :cry: 

I suspect it's not an issue anymore, so I close this one.

@wakkowarner Feel free to re-open it if you still need it!

**Comment by wakkowarner** [comment]
CentOS 5 reached it's EOL at March 31, 2017, so I guess this can be safely ignored...
